import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt({
  ignores: ['**/*__test.*'],
  name: 'portfolio/strict',
  rules: {
    // Reglas (JavaScript)
    'no-debugger': 'error',
    'no-undef': 'error',
    'eqeqeq': ['error', 'always'],
    'semi': ['error', 'always'],
    'quotes': ['error', 'single'],
    'no-var': 'error',
    'camelcase': 'error',
    'no-console': 'warn',
    'no-unused-vars': 'warn',
    'prefer-const': 'warn',
    // Reglas (Vue3)
    'vue/no-v-html': 'error',
    'vue/require-default-prop': 'off',
    'vue/max-attributes-per-line': ['error', { 'singleline': { 'max': 5 }, 'multiline': { 'max': 1 } }],
    'vue/require-prop-types': 'error',
    'vue/component-name-in-template-casing': ['error', 'PascalCase'],
    'vue/no-mutating-props': 'error',
    'vue/attribute-hyphenation': ['error', 'never'],
    'vue/no-async-in-computed-properties': 'error',
    'vue/no-computed-properties-in-data': 'error',
    'vue/no-dupe-keys': 'error',
    'vue/no-dupe-v-else-if': 'error',
    'vue/no-duplicate-attributes': ['error', { 'allowCoexistClass': true, 'allowCoexistStyle': true }],
    'vue/no-export-in-script-setup': 'error',
    'vue/no-reserved-component-names': 'error',
    'vue/return-in-computed-property': 'error',
    'vue/valid-attribute-name': 'error',
    'vue/valid-next-tick': 'error',
    'vue/valid-template-root': 'error',
    'vue/valid-v-cloak': 'error',
    'vue/valid-v-if': 'error',
    'vue/valid-v-else-if': 'error',
    'vue/valid-v-else': 'error',
    'vue/valid-v-for': 'error',
    'vue/valid-v-model': 'error',
    'vue/valid-v-show': 'error',
    'vue/valid-v-once': 'error',
    'vue/valid-v-slot': 'error',
    'vue/valid-v-text': 'error',
    'vue/valid-v-on': 'error',
    'vue/no-deprecated-data-object-declaration': 'error',
    'vue/no-deprecated-html-element-is': 'error',
    'vue/no-deprecated-v-is': 'error',
    'vue/no-deprecated-scope-attribute': 'error',
    'vue/no-deprecated-slot-attribute': 'error',
    'vue/no-lifecycle-after-await': 'error',
    'vue/no-v-for-template-key-on-child': 'error',
    'vue/no-watch-after-await': 'error',
    'vue/prefer-import-from-vue': 'error',
    'vue/multi-word-component-names': 'off',
    'vue/no-unused-components': 'warn',
    'vue/html-self-closing': 'warn',
    'vue/no-child-content': 'warn',
    'vue/html-indent': ['warn', 4, { 'baseIndent': 1, }],
    // Reglas (TypeScript)
    '@typescript-eslint/no-unused-vars': ['warn']
  }
});